# yaml-language-server: $schema=./Extensions/Environment.json
distributions:
  easy:
    rate: 0.01
    offset: 75
  medium:
    rate: 0.0033
    offset: 75
  hard:
    rate: 0.002
    offset: 75
  dummy:
    rate: .inf
    offset: 375
blocks:
  - &baseParameters
    weight: 1
    minDueTime: 60
    maxDueTime: 180
    patches:
      patch1: { distributionRef: easy }
      patch2: { distributionRef: easy }
      patch3: { distributionRef: easy }
      patchDummy1: { distributionRef: dummy }
  - <<: *baseParameters 
    patches:
      patch1: { distributionRef: easy }
      patch2: { distributionRef: medium }
      patch3: { distributionRef: hard }
      patchDummy1: { distributionRef: dummy }
  - <<: *baseParameters
    patches:
      patch1: { distributionRef: easy }
      patch2: { distributionRef: hard }
      patch3: { distributionRef: medium }
      patchDummy1: { distributionRef: dummy }
  - <<: *baseParameters
    patches:
      patch1: { distributionRef: medium }
      patch2: { distributionRef: easy }
      patch3: { distributionRef: hard }
      patchDummy1: { distributionRef: dummy }
  - <<: *baseParameters
    patches:
      patch1: { distributionRef: medium }
      patch2: { distributionRef: hard }
      patch3: { distributionRef: easy }
      patchDummy1: { distributionRef: dummy }
  - <<: *baseParameters
    patches:
      patch1: { distributionRef: hard }
      patch2: { distributionRef: easy }
      patch3: { distributionRef: medium }
      patchDummy1: { distributionRef: dummy }
  - <<: *baseParameters
    patches:
      patch1: { distributionRef: hard }
      patch2: { distributionRef: medium }
      patch3: { distributionRef: easy }
      patchDummy1: { distributionRef: dummy }
  - <<: *baseParameters
    patches:
      patch1: { distributionRef: hard }
      patch2: { distributionRef: hard }
      patch3: { distributionRef: hard }
      patchDummy1: { distributionRef: dummy }